Add windows installation

diff --git a/.github/workflows/cmake_install.yml b/.github/workflows/cmake_install.yml
--- a/.github/workflows/cmake_install.yml
+++ b/.github/workflows/cmake_install.yml
@@ -12,7 +12,7 @@ jobs:
 
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest]
+        os: [ubuntu-latest, macos-latest, windows-latest]
 
     steps:
     - name: Install tools on Ubuntu
@@ -22,6 +22,17 @@ jobs:
     - name: Install tools on macOS
       if: matrix.os == 'macos-latest'
       run: brew install tbb spdlog simdjson
+
+    - name: Install tools on Windows
+      if: matrix.os == 'windows-latest'
+      run: |
+        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
+        # Install vcpkg for spdlog, tbb, fmt, and simdjson on Windows
+        git clone https://github.com/Microsoft/vcpkg.git
+        cd vcpkg
+        .\bootstrap-vcpkg.bat
+        .\vcpkg install spdlog:x64-windows tbb:x64-windows fmt:x64-windows simdjson:x64-windows
+        echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" >> $env:GITHUB_ENV
 
     - name: Set environment variables on macOS
       if: matrix.os == 'macos-latest'
@@ -50,6 +61,15 @@ jobs:
         cmake --build .
         sudo cmake --install .
 
+    - name: Build and install on Windows
+      if: matrix.os == 'windows-latest'
+      working-directory: ${{github.workspace}}
+      run: |
+        mkdir -p build && cd build
+        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Release
+        cmake --build . --config Release
+        cmake --install .
+
     - name: Test include on Ubuntu
       if: matrix.os == 'ubuntu-latest'
       working-directory: ${{github.workspace}}
@@ -72,3 +92,11 @@ jobs:
           -ltbb -lfmt -lspdlog \
           && echo "Compiled successfully" \
           || (echo "Cannot include dsf" ; exit 1)
+
+    - name: Test include on Windows
+      if: matrix.os == 'windows-latest'
+      working-directory: ${{github.workspace}}
+      run: |
+        echo "#include <dsf/dsf.hpp>" > test.cpp
+        echo "int main() {}" >> test.cpp
+        cl.exe test.cpp /std:c++20 /I"$env:VCPKG_ROOT/installed/x64-windows/include" /link /LIBPATH:"$env:VCPKG_ROOT/installed/x64-windows/lib" && echo "Compiled successfully" || (echo "Cannot include dsf" ; exit 1)
