Change `dsm` to `dsf`

diff --git a/.github/workflows/cmake_install.yml b/.github/workflows/cmake_install.yml
--- a/.github/workflows/cmake_install.yml
+++ b/.github/workflows/cmake_install.yml
@@ -27,6 +27,6 @@ jobs:
       working-directory: ${{github.workspace}}
       run: |
         touch test.cpp
-        echo "#include <dsm/dsm.hpp>" >> test.cpp
+        echo "#include <dsf/dsf.hpp>" >> test.cpp
         echo "int main() {}" >> test.cpp
-        g++ test.cpp -std=c++20 && echo "Compiled successfully" || echo "Cannot include dsm"
+        g++ test.cpp -std=c++20 && echo "Compiled successfully" || echo "Cannot include dsf"
